[[redirects]]
  from = "/discord"
  to = "https://discord.gg/AmmNs8n"
  status = 301

[[redirects]]
  from = "/github"
  to = "https://github.com/rpl-skandakra"
  status = 301

[[redirects]]
  from = "/instagram"
  to = "https://instagram.com/rplskandakra.dev"
  status = 301